openapi: 3.0.3
info:
  title: AI Service API
  version: 1.0.0
paths:
  /ai/plan:
    post:
      summary: Generate a plan for a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task_type:
                  type: string
                  enum: [code, browse, fs]
                payload:
                  type: object
              required: [task_type, payload]
      responses:
        '200':
          description: Plan generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  steps:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                        input:
                          type: string
                        sequence:
                          type: integer
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /ai/health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
