openapi: 3.0.3
info:
  title: Task Service API
  version: 1.0.0
paths:
  /tasks:
    post:
      summary: Submit a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum: [code, browse, fs]
                payload:
                  type: object
              required: [type, payload]
      responses:
        '200':
          description: Task accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  status:
                    type: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    get:
      summary: List all tasks
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    status:
                      type: string
  /tasks/{id}:
    get:
      summary: Get task status/result
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task status/result
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  status:
                    type: string
                  result:
                    type: object
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /tasks/health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
